spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forget?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  flyway:
    locations: classpath:db/migration
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
